import React from 'react';
import { Star } from 'lucide-react';
import type { ProductReview } from '../../types';
import { getMediaUrl } from '../../services/portfolioApi';

export const ProductReviews: React.FC<{ reviews?: ProductReview[]; average?: number; count?: number }> = ({ reviews = [], average = 0, count = 0 }) => <section style={{ marginTop: '3rem', background: '#fff', border: '1px solid rgba(197,160,89,.3)', padding: '2rem' }}>
  <div style={{ display: 'flex', justifyContent: 'space-between', gap: '1rem', alignItems: 'center', flexWrap: 'wrap', borderBottom: '1px solid rgba(197,160,89,.2)', paddingBottom: '1rem' }}><div><span className="section-subtitle">EXPERIENCIAS REALES</span><h2 className="section-title" style={{ marginBottom: 0 }}>VALORACIONES & RESEÑAS</h2></div><div style={{ color: '#C5A059', display: 'flex', alignItems: 'center', gap: '.4rem' }}><Star fill="#C5A059" size={18} /> <strong>{average ? average.toFixed(1) : '0.0'}</strong><span style={{ color: '#7a6f64', fontSize: 11 }}>({count})</span></div></div>
  {reviews.length === 0 ? <p style={{ color: '#7a6f64', fontSize: 12, marginTop: '1.5rem' }}>Todavía no hay reseñas para este producto.</p> : <div style={{ display: 'grid', gap: '1.25rem', marginTop: '1.5rem' }}>{reviews.map(review => <article key={review.id} style={{ borderBottom: '1px solid rgba(197,160,89,.15)', paddingBottom: '1rem' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 12 }}><strong style={{ color: '#2c251e' }}>{review.author}</strong><span style={{ display: 'flex', gap: 2 }}>{[1,2,3,4,5].map(star => <Star key={star} size={13} fill={star <= review.rating ? '#C5A059' : 'none'} color="#C5A059" />)}</span></div><p style={{ color: '#5c5247', fontSize: 12, lineHeight: 1.7 }}>{review.text}</p>{review.media?.length ? <div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}>{review.media.map(media => media.type === 'VIDEO' ? <video key={media.id || media.url} src={getMediaUrl(media.url)} controls style={{ width: 140, height: 90, objectFit: 'cover' }} /> : <img key={media.id || media.url} src={getMediaUrl(media.url)} alt={media.altText || ''} style={{ width: 90, height: 90, objectFit: 'cover' }} />)}</div> : null}</article>)}</div>}
</section>;
