import React from 'react';
import { Link } from 'react-router-dom';
import { useCart } from '../shop/CartContext';

export const Cesta: React.FC = () => {
  const { items, total, updateQuantity, removeItem } = useCart();
  const [form, setForm] = React.useState({ customerName: '', customerEmail: '', customerPhone: '', address: '' });
  const [sent, setSent] = React.useState<string | null>(null);
  const submit = async () => { const base = import.meta.env.VITE_API_URL || (window.location.hostname === 'localhost' ? 'http://localhost:5000/api/portfolio' : 'https://alilyback.duckdns.org/eris/api/portfolio'); const response = await fetch(`${base}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, items: items.map(item => ({ productId: item.product.id, quantity: item.quantity })) }) }); const data = await response.json(); if (!response.ok) return alert(data.error || 'No se pudo crear el pedido'); setSent(`Pedido ${data.orderNumber} recibido. Te contactaremos para confirmar el pago y el envío.`); };
  return <div className="page-container"><div className="section-wrapper"><span className="section-subtitle">TU SELECCIÓN</span><h1 className="page-title">CESTA</h1>{sent ? <div style={{ background: '#fff', padding: '3rem', textAlign: 'center' }}><h2>{sent}</h2><Link to="/tienda" className="btn-gold-primary">VOLVER A LA TIENDA</Link></div> : items.length === 0 ? <div style={{ background: '#fff', padding: '3rem', textAlign: 'center' }}><p>Tu cesta está vacía.</p><Link to="/tienda" className="btn-gold-primary">EXPLORAR TIENDA</Link></div> : <div style={{ display: 'grid', gap: '1rem' }}>{items.map(item => <div key={item.product.id} style={{ background: '#fff', padding: '1rem', display: 'flex', gap: '1rem', alignItems: 'center', flexWrap: 'wrap' }}><img src={item.product.coverImage} alt={item.product.title} style={{ width: 80, height: 80, objectFit: 'cover' }} /><div style={{ flex: 1 }}><strong>{item.product.title}</strong><div>{item.product.price.toFixed(2)} €</div></div><input aria-label={`Cantidad de ${item.product.title}`} type="number" min="1" value={item.quantity} onChange={e => updateQuantity(item.product.id, Number(e.target.value))} style={{ width: 70, padding: '.5rem' }} /><button onClick={() => removeItem(item.product.id)} className="btn-gold-outline">Eliminar</button></div>)}<div style={{ background: '#fff', padding: '1.5rem' }}><strong>Total: {total.toFixed(2)} €</strong><div style={{ display: 'grid', gap: '.6rem', marginTop: '1rem', maxWidth: 500 }}><input placeholder="Nombre completo" value={form.customerName} onChange={e => setForm({ ...form, customerName: e.target.value })} /><input type="email" placeholder="Email" value={form.customerEmail} onChange={e => setForm({ ...form, customerEmail: e.target.value })} /><input placeholder="Teléfono" value={form.customerPhone} onChange={e => setForm({ ...form, customerPhone: e.target.value })} /><input placeholder="Dirección de envío" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} /><button className="btn-gold-primary" onClick={submit}>ENVIAR PEDIDO</button></div></div></div>}</div></div>;
};
